@crear_proyecto
@crear_institucion
@crear_emple
@crear_materia
@crear_articulo
@crear_ins_pro
@crear_emp_emp
@crear_emp_tra_pro
@crear_emp_inv_pro
@crear_materia_especial
@crear_materia_no_especial
@crear_mat_art
@crear_mat_pro